### ISSUE TITLE
BUG: creating database joining employees and a distribution centre

### ISSUE THREAD

**Issue by sctowers** [ThomasLoughran/DeliverEase_app#1]
- in postico a 2nd join table distribution_centre_employees was created instead of employees being joined only to the distribution_centre table

**Comment by sctowers** [comment]
- Resolved by changing from snake to Pascal case. For example: 
```
@OneToMany(mappedBy = "distributionCentre") 
```

**Comment by sctowers** [comment]
- Resolved by making the properties match the table annotation names. For example: 
```
@OneToMany(mappedBy = "distributionCentre") 
```

**Comment by billieredwood** [comment]
**team noted for future reference**: 1) the Table name should be given a (here, snake_case ) **name**; 2) the relationship (e.g. 1-many) should be given a mappedBy value that is an exact match to the chosen **class**’s (in this instance, camelCase) **property**.’
